eyss1234/artly

Gemfile
Gemfile.lock
app/models/user.rb
app/views/devise/confirmations/new.html.erb
app/views/devise/mailer/confirmation_instructions.html.erb
app/views/devise/mailer/email_changed.html.erb
app/views/devise/mailer/password_change.html.erb
app/views/devise/mailer/reset_password_instructions.html.erb
app/views/devise/mailer/unlock_instructions.html.erb
app/views/devise/passwords/edit.html.erb
app/views/devise/passwords/new.html.erb
app/views/devise/registrations/edit.html.erb
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb
app/views/devise/shared/_error_messages.html.erb
app/views/devise/shared/_links.html.erb
app/views/devise/unlocks/new.html.erb
config/initializers/devise.rb
config/locales/devise.en.yml
config/routes.rb
db/migrate/20220730143301_devise_create_users.rb
db/schema.rb
test/models/user_test.rb

created basic user model, haven't added address yet.

devise user model initiated

---

app/controllers/art_pieces_controller.rb
app/models/art_piece.rb
db/migrate/20220730145540_create_art_pieces.rb
db/schema.rb
test/controllers/art_pieces_controller_test.rb
test/models/art_piece_test.rb

Created art_piece model and controller

add art model and controller

---

app/controllers/bookings_controller.rb
app/models/booking.rb
db/migrate/20220730151231_create_bookings.rb
db/schema.rb
test/controllers/bookings_controller_test.rb
test/models/booking_test.rb

Added booking model and controller

booking model and controller

---

db/migrate/20220730152334_add_cost_to_art_pieces.rb
db/schema.rb

added cost_per_day as integer column to the Art model

added cost per day to art

---

db/migrate/20220730151811_add_address_to_users.rb
db/schema.rb

add an address column to the user model

Add address column

---

.gitignore
Gemfile
Gemfile.lock
app/models/art_piece.rb
config/environments/development.rb
config/environments/production.rb
config/storage.yml
db/migrate/20220802181659_create_active_storage_tables.active_storage.rb
db/schema.rb

changes made in models, gemfile, configs, storage.yml to include photo storage.

added active_storage and photo association to model, including config

---

app/models/art_piece.rb
app/models/booking.rb
app/models/user.rb

A few questions:
- Do we need to create a dependent: :destroy ?
- Do we need to validate that the start date and end date allow only integers? Maybe we don't need that if the front-end is showing a calendar

add art_piece, booking, user associations

---

app/models/art_piece.rb
app/models/booking.rb
app/models/user.rb

Moved dependency to user model

moved dependent destroy to user model

---

app/controllers/art_pieces_controller.rb
app/controllers/bookings_controller.rb
app/policies/booking_policy.rb
config/storage.yml
test/policies/booking_policy_test.rb

added booking policy, booking controller methods with pundit

added pundit for bookings and basic booking controller actions

---

app/views/layouts/application.html.erb
app/views/shared/_navbar2.html.erb
config/initializers/assets.rb

Added a link on logo image to show page art pieces 
i commented out  line  10 in application.html.erb , we don t need it for now/ but for sure in the future.
But because of my vs code setting  it breaks the code if i have it in.
LINE COMMENTED OUT 
<%# <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>

link to show page art pieces added on logo image

---

app/assets/stylesheets/components/_navbar.scss

sticky navbar

---

app/controllers/application_controller.rb
app/controllers/users/registrations_controller.rb
app/controllers/users/sessions_controller.rb
app/views/devise/registrations/new.html.erb
app/views/layouts/application.html.erb

hey guys -
fixed the sign up form by adding :address to the form & adding :address to the params.require

added permissions for address to enable signup

---

app/assets/stylesheets/components/_art_piece_cards.scss
app/assets/stylesheets/components/_navbar.scss
app/views/shared/_art_piece_cards.html.erb

added an 'owner' flag on index page for self owned art

Index owner flag

---

app/assets/stylesheets/components/_art_piece_cards.scss
app/assets/stylesheets/components/_navbar.scss
app/views/art_pieces/show.html.erb
app/views/shared/_art_piece_cards.html.erb
app/views/shared/_booking_form.html.erb
config/routes.rb

added a delete option to art owned by a user

Art delete option

---

app/assets/stylesheets/pages/_show.scss
app/controllers/art_pieces_controller.rb
app/controllers/bookings_controller.rb
app/models/art_piece.rb
app/views/art_pieces/show.html.erb
app/views/layouts/application.html.erb
app/views/shared/_flashes.html.erb
app/views/shared/_upcoming_bookings.html.erb

booking that overlaps existing bookings not processed & alert flashes. question is how do we make dates unavailable to select??
anyways this is a good start.

Booking validity check

---

app/assets/stylesheets/pages/_show.scss
app/controllers/art_pieces_controller.rb
app/models/art_piece.rb
app/views/art_pieces/show.html.erb
app/views/shared/_upcoming_bookings.html.erb

Note that the delete button kept going to the art_piece_path and throwing an error instead of back to the index page. couldn't resolve, to built an error catch into the set_art_piece method as a fix for now. 
would be good if someone has a nother look @ this (or we raise a ticket on Tuesday)

added delete option and bookings list on show page

---

app/views/art_pieces/show.html.erb
app/views/shared/_booking_form.html.erb

in calendar, can't select historic dates

added min date as today + 1

---

app/controllers/users_controller.rb
app/policies/user_policy.rb
app/views/users/show.html.erb
config/routes.rb
test/controllers/users_controller_test.rb
test/policies/user_policy_test.rb

Done:
- added users show page to routes
- user pundit doesn't allow users to see other user pages, only it's own
- created show method in the controller
- created a view page that displays users-owned artwork. No styling added
Todo:
- maybe add a button for the user profile in the navbar
- add new art piece to rent button
- add upcoming bookings card
- add styling

add user show to routes, create user pundit, controller and basic view

---

app/controllers/application_controller.rb
app/controllers/art_pieces_controller.rb
app/controllers/bookings_controller.rb
app/views/shared/_booking_form.html.erb
app/views/shared/_index_filter_form.html.erb
config/routes.rb

added min. date = today + 1 to the html form

Min date on index filter form

---

app/controllers/application_controller.rb
app/controllers/art_pieces_controller.rb
app/controllers/bookings_controller.rb
app/views/shared/_booking_form.html.erb
config/routes.rb

upon sign in, users are now redirected to index page.

redirect achieved

---

app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_user_booking_cards.scss
app/models/user.rb
app/views/shared/_user_part_bookings.html.erb
app/views/shared/_user_upcoming_bookings.html.erb
app/views/users/show.html.erb

user show page with upcoming rentals, past rentals and owners art pieces

---

app/views/art_pieces/index.html.erb
app/views/shared/_index_filter_form.html.erb

Stick index menu

---

app/javascript/controllers/index.js
app/javascript/controllers/indexform_controller.js
app/views/shared/_index_filter_form.html.erb

this now updates the indexform min end date to match the selected start date

Update min date on index form

---

app/controllers/art_pieces_controller.rb

fixed issue with empty dates by building in logic to check for empty dates

Fix issue with empty end date

---

app/assets/stylesheets/pages/_home.scss
app/javascript/application.js
app/views/layouts/application.html.erb
app/views/pages/home.html.erb
package.json
yarn.lock

please check only this one as i had to comment out again the special line in application.html 
i added typed.js to banner text

Addtypedtolandpage

---

app/views/art_pieces/edit.html.erb
app/views/art_pieces/new.html.erb
app/views/art_pieces/show.html.erb
app/views/bookings/edit.html.erb
app/views/shared/_art_form.html.erb
app/views/shared/_user_upcoming_bookings.html.erb
app/views/users/show.html.erb

added back buttons throughout, leading back to Gallery, Art Piece, or User page accordingly

Back buttons

---

app/assets/stylesheets/pages/_index.scss
app/models/review.rb
app/views/art_pieces/index.html.erb
app/views/shared/_index_filter_form.html.erb
db/migrate/20220811165757_create_reviews.rb
db/schema.rb
test/models/review_test.rb

added model 
haven't done associations or anything

review model created

---

.gitignore
app/assets/config/manifest.js
app/views/shared/_navbar2.html.erb

Navbar user profile button

---

app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/config/_colors.scss
app/views/shared/_navbar2.html.erb

- added CSS styling with Emily (nice box with shadow, padding)
- added hover effect (orange background on hover)
- added font awesome icons
- removed dropdown box toggle when the user isn't signed in, since only one menu item (2 clicks seemed excessive here). so when they haven't logged in, it just says 'log in' directly on the navbar

Navbar links

---

app/assets/stylesheets/components/_alert.scss
app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/config/_colors.scss
app/views/shared/_navbar2.html.erb
config/locales/devise.en.yml

- updated styling to match theme
- centered the popup
- removed flashes for sign in and sign out

Error message placement

---

app/models/booking.rb
app/models/rating.rb

added validations to review model

add validations to review model

---

app/controllers/ratings_controller.rb
config/routes.rb
test/controllers/ratings_controller_test.rb

creating ratings controller

---

app/controllers/ratings_controller.rb
app/policies/rating_policy.rb
test/policies/rating_policy_test.rb

we added pundit to review model

review pundit

---

app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/pages/_index.scss
app/controllers/art_pieces_controller.rb
app/views/art_pieces/index.html.erb
app/views/shared/_index_filter_form.html.erb
app/views/shared/_navbar2.html.erb
app/views/shared/_sort_menu.html.erb

just changed navbar to position-sticky

Sticky nav

---

app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/pages/_index.scss
app/controllers/art_pieces_controller.rb
app/views/art_pieces/index.html.erb
app/views/shared/_index_filter_form.html.erb
app/views/shared/_navbar2.html.erb
app/views/shared/_sort_menu.html.erb

side bar back to sticking again, using grid and offset from bootstrap. 
at smallest screen size when the form is size col12, we remove the position: fixed and let the menu move up with scroll.

Sticky side

---

app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/pages/_index.scss
app/controllers/art_pieces_controller.rb
app/views/art_pieces/index.html.erb
app/views/shared/_index_filter_form.html.erb
app/views/shared/_navbar2.html.erb
app/views/shared/_sort_menu.html.erb

this way, both are applied simultaneously.

merged both sort and filters into one form

---

app/models/rating.rb

added rating validations
